### ISSUE TITLE
Plugin installation issue 

### ISSUE THREAD

**Issue by anttoon** [athombv/node-homey-rfdriver#14]
`ENOENT: no such file or directory, open '/Users/<user>/<project>/node_modules/homey-rfdriver/compose/driver/driver.js'`

Guessing it should point to `.compose` instead of `compose`:
`'/Users/<user>/<project>/node_modules/homey-rfdriver/.compose/driver/driver.js'`
Or am I missing something?

**Comment by BasKiers** [comment]
Hi, 

Thanks for your bug report! 
This will be fixed in the next version of Athom-Cli.

Regards,
Bas

**Comment by BasKiers** [comment]
I will close this issue, you can follow the bugfix here: https://github.com/athombv/node-athom-cli/pull/61
